### ISSUE TITLE
Using entrypoint disable persistence volumes docker-compose 

### ISSUE THREAD

**Issue by noonenene** [RediSearch/RediSearch#2996]
Using this file loads redisearch fine but disable persistence.
How can i use docker-compose with persistence, password and redisearch.so?

```
version: "3.9"
services:
  redis:
    container_name: redis-stack-server
    image: "redis/redis-stack-server:latest"
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    entrypoint:
      redis-server
        --loadmodule /opt/redis-stack/lib/redisearch.so
        --loadmodule /opt/redis-stack/lib/rejson.so
        --requirepass "password"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
```
