### ISSUE TITLE
Please Help Fix RSCoordinator So that Redis Search (RediSearch) Can Be Used Across Redis Cluster - module-oss.so initialization failed

### ISSUE THREAD

**Issue by xtianus79** [RediSearch/RediSearch#4588]
I first want to say that I love Redis and am a huge fan and advocate for the product. I work in 2 capacities. I work on my own projects and I work in an enterprise setting which has full access to Redis. However, it is always a "convincing" when I pull out the Redis toolbox because it's not first party. In this way, what I learn from my personal projects (and dreams) gives me the knowledge to explain why we should go with Redis in given situations. 

For years, I have been planning on tackling redis search as opposed to other offerings. Now is the time I am trying to implement it for my personal projects. This issue has been asked for and spoken about on countless threads with no real answers. In fact, there seems to be an odd aversion to answering the queries in earnest as to give a proper solution. 

Very simply, is RSCoordinator available through Redis-Cluster or not? If it is supported than can we fix these issues? I did my part may I have help getting it across the finish line. 

https://forum.redis.io/t/anything-to-do-to-get-redisearch-to-search-across-clusters/1943 (this is the most confusing)
https://forum.redis.io/t/how-can-i-handle-redis-cluster-with-redis-stack-redisearch/2186/2
https://github.com/RediSearch/RediSearch/issues/4565
https://github.com/redis/redis-py/issues/2365
https://github.com/redis/redis-py/pull/2470
https://github.com/RediSearch/RediSearch/issues/3147
https://github.com/redis-stack/redis-stack/issues/531
https://github.com/RediSearch/RediSearch/issues/25 (2017) 
> [dvirsky](https://github.com/dvirsky) commented [on Jun 6, 2017](https://github.com/RediSearch/RediSearch/issues/25#issuecomment-306509804)
Fixed in a previous version.

> i forked the repo and fixed a ton of errors. You could use rlec here too but I don't know how that would work on redis oss.
https://github.com/xtianus79/RediSearch/tree/master

```bash
git submodule update --init --recursive
cd coord
cmake -DCOORD_TYPE=oss .
make
```

> this is a sub module that I had to fix too for reference (don't need it for build)
https://github.com/xtianus79/RedisLabsModules-readies/tree/master

When I load the module into my cluster I get this module initialization error. 

```bash
# Module /opt/bitnami/redis/etc/module-oss.so initialization failed. Module not loaded
# Can't load module from /opt/bitnami/redis/etc/module-oss.so: server aborting
```
Any real help would be appreciated. I would love to PR any work back into Redis.

**Comment by GuyAv46** [comment]
Hello @xtianus79, thanks for reaching out!
Simply answering - yes. RediSearch is available for clustering.
You’ll have to run (from the project’s root directory) `make COORD=1` and take the same file you were trying to.
I think that the way you compiled the project missed some internal library building.
Let me know if you need further assistance.

**Comment by AllKai** [comment]
> Hello @xtianus79, thanks for reaching out! Simply answering - yes. RediSearch is available for clustering. You’ll have to run (from the project’s root directory) `make COORD=1` and take the same file you were trying to. I think that the way you compiled the project missed some internal library building. Let me know if you need further assistance.

I've been struggling with this issue for two days without finding a solution. It may be due to the limitations imposed by the Kubernetes environment in the pod. If RedisSearch supports cluster mode, why not include this functionality directly in the redisearch.so file, instead of requiring a recompilation with make build COORD=1?

**Comment by xtianus79** [comment]
@GuyAv46 it's still not working. 

I switched it around and built it with make && make COORD=1 instead of my build. everything is working and transferred into the build. 

```
1:M 09 Apr 2024 07:36:22.403 # Module /opt/bitnami/redis/etc/module-oss.so initialization failed. Module not loaded
1:M 09 Apr 2024 07:36:22.403 # Can't load module from /opt/bitnami/redis/etc/module-oss.so: server aborting
```

here is the ldd 

```bash
 linux-vdso.so.1 (0x00007ffdd29e9000)
        libcrypto.so.1.1 => /lib/x86_64-linux-gnu/libcrypto.so.1.1 (0x00007f909b395000)
        libssl.so.1.1 => /lib/x86_64-linux-gnu/libssl.so.1.1 (0x00007f909b302000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f909b2fd000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f909b21e000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f909b1fe000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f909b1f7000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f909b016000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f909bcf7000)
```

**Comment by GuyAv46** [comment]
I'm assuming you are compiling against a clean branch with no `cmake` files leftovers from your previous attempt.
What redis version are you using?
Is it possible that you have another version of the RediSearch module loaded? since there is no additional log message it may suggest that the module name is already taken

**Comment by xtianus79** [comment]
hi @GuyAv46 

> these libraries are coming from OpenSSL 1.1. you can also try to install it to have them on the server.

I am putting these libraries on the server they are from debian image. Is this what you mean? 

> But your problem is that you cannot load both redisearch.so and module-oss.so, because they are both the RediSearch module, and both attempt to register themselves by the name "search" internally.
You don't need the redisearch.so if you want to use the module-oss.so that contains it + the option of cross-shard communication and search.

Ok, so you're saying if we use module-oss.so then we don't need to load in search? 

> Note that for a single-shard topology, you will experience some overhead by using module-oss.so instead of redisearch.so

So for more than 1 shard this is good but if using only one node/shard then it would be overkill?

**Comment by GuyAv46** [comment]
1. Yes
2. Yes. It's the same module with additional capabilities. And you cannot load the same module twice.
3. It would work for a single-shard topology. If you want the capability to change the number of nodes in runtime then you have to use the `module-oss.so`. If you have a case where you don't need more than one shard and don't need to scale, you may be better off using the `redisearch.so` option. On the other hand, if you take the current `master` version you'll actually won't suffer any overhead

**Comment by xtianus79** [comment]
@GuyAv46 hi. I think I am close but this in my docker-compose testing I am getting this error with the module-oss

do I just have to overcome this or is there something specific I should know. 

```bash
1:M 09 Apr 2024 20:12:09.258 * <ReJSON> Exported RedisJSON_V4 API
1:M 09 Apr 2024 20:12:09.258 * <ReJSON> Exported RedisJSON_V5 API
1:M 09 Apr 2024 20:12:09.258 * <ReJSON> Enabled diskless replication
1:M 09 Apr 2024 20:12:09.258 * Module 'ReJSON' loaded from /opt/bitnami/redis/etc/rejson.so
1:M 09 Apr 2024 20:12:09.259 * <search> redis version observed by redisearch : 7.2.4
1:M 09 Apr 2024 20:12:09.259 * <search> Redis version found by RedisSearch : 7.2.4 - oss
1:M 09 Apr 2024 20:12:09.259 * <search> RediSearch version 2.8.12 (Git=HEAD-86206d496)
1:M 09 Apr 2024 20:12:09.259 * <search> Low level api version 1 initialized successfully
1:M 09 Apr 2024 20:12:09.259 * <search> Acquired RedisJSON_V5 API
1:M 09 Apr 2024 20:12:09.259 * <search> concurrent writes: OFF, gc: ON, prefix min length: 2, prefix max expansions: 200, query timeout (ms): 500, timeout policy: return, cursor read size: 1000, cursor max idle (ms): 300000, max doctable size: 1000000, max number of search results:  1000000, search pool size: 20, index pool size: 8,
1:M 09 Apr 2024 20:12:09.260 * <search> Initialized thread pools!
1:M 09 Apr 2024 20:12:09.260 * <search> Enabled role change notification
1:M 09 Apr 2024 20:12:09.260 * <search> Cluster configuration: 0 partitions, type: 0, coordinator timeout: 0ms
Creating thread...
Thread created
1:M 09 Apr 2024 20:12:09.260 * <search> Register write commands
1:M 09 Apr 2024 20:12:09.260 * Module 'search' loaded from /opt/bitnami/redis/etc/module-oss.so
1:M 09 Apr 2024 20:12:09.260 # Warning: Could not create server TCP listening socket ::1:6379: bind: Cannot assign requested address
1:M 09 Apr 2024 20:12:09.260 # Warning: Could not create server TCP listening socket ::1:16379: bind: Cannot assign requested address
1:M 09 Apr 2024 20:12:09.260 * Server initialized
1:M 09 Apr 2024 20:12:09.261 * Ready to accept connections tcp
1:M 09 Apr 2024 20:12:10.260 # <search> Got no slots in CLUSTER SLOTS
1:M 09 Apr 2024 20:12:11.260 # <search> Got no slots in CLUSTER SLOTS
1:M 09 Apr 2024 20:12:12.260 # <search> Got no slots in CLUSTER SLOTS
1:M 09 Apr 2024 20:12:13.261 # <search> Got no slots in CLUSTER SLOTS
1:M 09 Apr 2024 20:12:14.261 # <search> Got no slots in CLUSTER SLOTS
1:M 09 Apr 2024 20:12:15.261 # <search> Got no slots in CLUSTER SLOTS
1:M 09 Apr 2024 20:12:16.261 # <search> Got no slots in CLUSTER SLOTS
1:M 09 Apr 2024 20:12:17.261 # <search> Got no slots in CLUSTER SLOTS
```

**Comment by xtianus79** [comment]
@GuyAv46 I'm almost there but I am getting this error now. Still, I am can't use it.

`(error) ERR Protocol error: unauthenticated multibulk length`

I saw this quote here that slightly relates https://github.com/Significant-Gravitas/AutoGPT/issues/562 
> Make sure your password is configured in .env and try an AUTH command with the password to test locally.

I have it loaded and I no longer have the issue with the CLUSTER SLOTS as that seems to be an issue with the docker-compose and loading modules. 

The thing is I the authentication is set via password. The entire redis server works all except for search

I don't really find anything in the logs except for this

```bash
[0x7f0a16a0b080 52.224.233.90:6379 Connected]Switching state to Connecting
[0x7f0a16a0b080 52.224.233.90:6379 Connecting]Error on connect:
[0x7f0a16a0b080 52.224.233.90:6379 Connecting]Switching state to Connecting
[0x7f0a16a0b000 52.224.216.24:6379 Connected]Switching state to Connecting
[0x7f0a16a0b000 52.224.216.24:6379 Connecting]Error on connect:
```

**Comment by GuyAv46** [comment]
I believe what you’re missing now is the `OSS_GLOBAL_PASSWORD` configuration. If you’re using `AUTH` to connect to the cluster you need to supply the password to the module, so it can connect to the other shards with his hiredis clients

**Comment by xtianus79** [comment]
@GuyAv46 BOOM NICE!!! I am 99% There. Just checking a few more things. 
QQ, the global password can be from a created user and password or does it need to be a root user and password?

**Comment by xtianus79** [comment]
@GuyAv46 update. I have it 100% working in k8s cluster so thank you for the help. I had to clear/delete my storage and got it working smoothly. 

1 last thing. I cannot get it working for the local docker-compose.yml as I keep getting this error because the cluster is failing specifically on this module. I can't get the cluster to run with the module-oss loaded. 

```bash
:M 11 Apr 2024 05:23:15.673 # <search> Got no slots in CLUSTER SLOTS
1:M 11 Apr 2024 05:23:16.674 # <search> Got no slots in CLUSTER SLOTS
```

i've tried everything. would it be better to just run separate docker containers and connect them together for texting and avoid the docker compose? 

here are my settings x 6. this is just for testing locally. Let me know if I should open a separate issue for this. 

```bash
bind 127.0.0.1 -::1
protected-mode yes
port 6379
tcp-backlog 511
timeout 0
tcp-keepalive 300
daemonize no
pidfile /opt/bitnami/redis/tmp/redis-6379.pid
loglevel notice
logfile ""
databases 16
always-show-logo no
set-proc-title yes
proc-title-template "{title} {listen-addr} {server-mode}"
locale-collate ""
stop-writes-on-bgsave-error yes
rdbcompression yes
rdbchecksum yes
dbfilename dump-6379.rdb
rdb-del-sync-files no
dir /bitnami/redis/data/6379
replica-serve-stale-data yes
replica-read-only yes
repl-diskless-sync yes
repl-diskless-sync-delay 5
repl-diskless-sync-max-replicas 0
repl-diskless-load disabled
repl-disable-tcp-nodelay no
replica-priority 100
acllog-max-len 128
lazyfree-lazy-eviction no
lazyfree-lazy-expire no
lazyfree-lazy-server-del no
replica-lazy-flush no
lazyfree-lazy-user-del no
lazyfree-lazy-user-flush no
oom-score-adj no
oom-score-adj-values 0 200 800
disable-thp yes
appendonly no
appendfilename "appendonly-6379.aof"
appenddirname "appendonlydir"
appendfsync everysec
no-appendfsync-on-rewrite no
auto-aof-rewrite-percentage 100
auto-aof-rewrite-min-size 64mb
aof-load-truncated yes
aof-use-rdb-preamble yes
aof-timestamp-enabled no
cluster-enabled yes
cluster-config-file /bitnami/redis/data/nodes-6379.conf
slowlog-log-slower-than 10000
slowlog-max-len 128
latency-monitor-threshold 0
notify-keyspace-events ""
hash-max-listpack-entries 512
hash-max-listpack-value 64
list-max-listpack-size -2
list-compress-depth 0
set-max-intset-entries 512
set-max-listpack-entries 128
set-max-listpack-value 64
zset-max-listpack-entries 128
zset-max-listpack-value 64
hll-sparse-max-bytes 3000
stream-node-max-bytes 4096
stream-node-max-entries 100
activerehashing yes
client-output-buffer-limit normal 0 0 0
client-output-buffer-limit replica 256mb 64mb 60
client-output-buffer-limit pubsub 32mb 8mb 60
hz 10
dynamic-hz yes
aof-rewrite-incremental-fsync yes
rdb-save-incremental-fsync yes
jemalloc-bg-thread yes
enable-module-command yes
requirepass bitnami
```
```yaml
# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: '2'
services:
  redis-node-0:
    image: my-redis-with-modules:latest
    volumes:
      - redis-cluster_data-0:/bitnami/redis/data/6379
      - ./redis-6379.conf:/opt/bitnami/redis/etc/redis.conf
    environment:
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'
      - 'REDIS_PASSWORD=bitnami'
    command: "redis-server /opt/bitnami/redis/etc/redis.conf --loadmodule /opt/bitnami/redis/etc/rejson.so --loadmodule /opt/bitnami/redis/etc/module-oss.so OSS_GLOBAL_PASSWORD bitnami"
    networks:
      - redis-cluster-net
    ports:
      - "6379:6379"

  redis-node-1:
    image: my-redis-with-modules:latest
    volumes:
      - redis-cluster_data-1:/bitnami/redis/data/6380
      - ./redis-6380.conf:/opt/bitnami/redis/etc/redis.conf
    environment:
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'
      - 'REDIS_PASSWORD=bitnami'
    command: "redis-server /opt/bitnami/redis/etc/redis.conf --loadmodule /opt/bitnami/redis/etc/rejson.so --loadmodule /opt/bitnami/redis/etc/module-oss.so OSS_GLOBAL_PASSWORD bitnami"
    networks:
      - redis-cluster-net
    ports:
      - "6380:6380"

  redis-node-2:
    image: my-redis-with-modules:latest
    volumes:
      - redis-cluster_data-2:/bitnami/redis/data/6381
      - ./redis-6381.conf:/opt/bitnami/redis/etc/redis.conf
    environment:
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5 '
      - 'REDIS_PASSWORD=bitnami'
    command: "redis-server /opt/bitnami/redis/etc/redis.conf --loadmodule /opt/bitnami/redis/etc/rejson.so --loadmodule /opt/bitnami/redis/etc/module-oss.so OSS_GLOBAL_PASSWORD bitnami"
    networks:
      - redis-cluster-net
    ports:
      - "6381:6381"

  redis-node-3:
    image: my-redis-with-modules:latest
    volumes:
      - redis-cluster_data-3:/bitnami/redis/data/6382
      - ./redis-6382.conf:/opt/bitnami/redis/etc/redis.conf
    environment:
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'
      - 'REDIS_PASSWORD=bitnami'
    command: "redis-server /opt/bitnami/redis/etc/redis.conf --loadmodule /opt/bitnami/redis/etc/rejson.so --loadmodule /opt/bitnami/redis/etc/module-oss.so OSS_GLOBAL_PASSWORD bitnami"
    networks:
      - redis-cluster-net
    ports:
      - "6382:6382"

  redis-node-4:
    image: my-redis-with-modules:latest
    volumes:
      - redis-cluster_data-4:/bitnami/redis/data/6383
      - ./redis-6383.conf:/opt/bitnami/redis/etc/redis.conf
    environment:
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'
      - 'REDIS_PASSWORD=bitnami'
    command: "redis-server /opt/bitnami/redis/etc/redis.conf --loadmodule /opt/bitnami/redis/etc/rejson.so --loadmodule /opt/bitnami/redis/etc/module-oss.so OSS_GLOBAL_PASSWORD bitnami"
    networks:
      - redis-cluster-net
    ports:
      - "6383:6383"

  redis-node-5:
    image: my-redis-with-modules:latest
    volumes:
      - redis-cluster_data-5:/bitnami/redis/data/6384
      - ./redis-6384.conf:/opt/bitnami/redis/etc/redis.conf
    depends_on:
      - redis-node-0
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
    environment:
      - 'REDIS_PASSWORD=bitnami'
      - 'REDISCLI_AUTH=bitnami'
      - 'REDIS_CLUSTER_REPLICAS=1'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'
      - 'REDIS_CLUSTER_CREATOR=yes'
    command: "redis-server /opt/bitnami/redis/etc/redis.conf --loadmodule /opt/bitnami/redis/etc/rejson.so --loadmodule /opt/bitnami/redis/etc/module-oss.so OSS_GLOBAL_PASSWORD bitnami"
    networks:
      - redis-cluster-net
    ports:
      - "6384:6384"

volumes:
  redis-cluster_data-0:
    driver: local
  redis-cluster_data-1:
    driver: local
  redis-cluster_data-2:
    driver: local
  redis-cluster_data-3:
    driver: local
  redis-cluster_data-4:
    driver: local
  redis-cluster_data-5:
    driver: local

networks:
  redis-cluster-net:
    driver: bridge
```
