### ISSUE TITLE
[BUG] FT.CREATE command does not work and hangs in a cluster

### ISSUE THREAD

**Issue by gottlike** [RediSearch/RediSearch#6324]
**Describe the bug**

When using "redis-cli" or the Ruby "redis" + "redis-clustering" library, all attempts to use `FT.CREATE` fail. The command never responds (process has to be terminated) and does not create a new index.

**To reproduce**

Use the official Redis 8.0.1 Docker image to set up a cluster of 3 master nodes. Log into a shard and try to create any index with `FT.CREATE`.

**Expected behavior**

Should respond with "OK" and create the index.

**Environment**

Official Redis 8.0.1 docker image.

**Additional information**

The search module is active, I checked.

**Comment by gottlike** [comment]
Here's a quick Ruby script for testing this with a similar config to mine:

```ruby
#!/usr/bin/env ruby

require 'redis'
require 'redis-clustering'

redis = Redis::Cluster.new(
  nodes: ['rediss://:pass@1.example.com:6379', 'rediss://:pass@2.example.com:6379', 'rediss://:pass@3.example.com:6379']
)

begin
  # Test connection
  puts 'Testing Redis connection...'
  redis.ping
  puts '✓ Connected to Redis successfully'

  # Check if RediSearch is available
  puts 'Checking for RediSearch module...'
  modules = redis.call('MODULE', 'LIST')
  has_search = modules.any? { |mod| mod[1].include?('search') }

  if has_search
    puts '✓ RediSearch module found'
  else
    puts '✗ RediSearch module not found'
    exit 1
  end

  # Create the index
  puts 'Creating user index...'
  redis.call('FT.CREATE', 'user_idx', 'ON', 'HASH', 'PREFIX', '1', 'user/',
             'SCHEMA', 'something', 'TAG')

  puts "✓ Index 'user_idx' created successfully!"
rescue Redis::CommandError => e
  if e.message.include?('Index already exists')
    puts "ℹ Index 'user_idx' already exists"
  else
    puts "✗ Error: #{e.message}"
  end
rescue StandardError => e
  puts "✗ Error: #{e.message}"
end
```

**Comment by kei-nan** [comment]
Tried using the equivalent python script with a cluster of 3 nodes(outside of a docker container) and it seemed to worked:
```
from redis.cluster import RedisCluster
from redis.exceptions import RedisError

try:
    print("Testing Redis connection...")
    # Connect to the Redis cluster via one node; discovery happens automatically
    redis = RedisCluster(host="127.0.0.1", port=30001, decode_responses=True)
    redis.ping()
    print("✓ Connected to Redis successfully")

    print("Checking for RediSearch module...")
    modules = redis.execute_command("MODULE", "LIST")
    has_search = any("search" in mod[1].lower() for mod in modules)

    if has_search:
        print("✓ RediSearch module found")
    else:
        print("✗ RediSearch module not found")
        exit(1)

    print("Creating user index...")
    try:
        redis.execute_command(
            "FT.CREATE", "user_idx", "ON", "HASH", "PREFIX", "1", "user/",
            "SCHEMA", "something", "TAG"
        )
        print("✓ Index 'user_idx' created successfully!")
    except RedisError as e:
        if "Index already exists" in str(e):
            print("ℹ Index 'user_idx' already exists")
        else:
            print(f"✗ Error creating index: {e}")

except Exception as e:
    print(f"✗ Error: {e}")
```
Can you share how you are creating the cluster? A docker compose yml file would probably be best if that is available.
Since you are using a docker container do all the nodes share the same network and can reach one another?

**Comment by gottlike** [comment]
Thanks for your prompt reply. So it seems it's not a cluster, but a Docker issue then. Here's my full compose file for one node:

```yaml
services:
  caddy:
    container_name: caddy
    image: caddy:2.10-alpine
    restart: always
    ports:
    - 80:80
    - 443:443
    - 443:443/udp
    volumes:
    - "/root/caddy/Caddyfile/:/etc/caddy/Caddyfile/"
    - "/root/caddy/content/:/srv/"
    - "/root/caddy/caddy_data/:/data/"
    - "/root/caddy/caddy_config/:/config/"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    logging:
      driver: json-file
      options:
        max-file: 1
        max-size: 50m
  redis:
    container_name: redis
    image: redis:8-alpine
    depends_on:
    - caddy
    restart: always
    ports:
    - 6379:6379
    - 16379:16379
    command: "--requirepass password --masterauth password --appendonly
      yes --appendfsync everysec --auto-aof-rewrite-percentage 100 --auto-aof-rewrite-min-size
      64mb --save 300 1 --tls-port 6379 --cluster-port 16379 --cluster-announce-tls-port
      0 --cluster-announce-port 6379 --cluster-announce-bus-port 16379 --port 0 --cluster-announce-hostname
      1.example.com --cluster-preferred-endpoint-type hostname --tls-auth-clients
      no --tls-replication no --tls-cluster no --tls-cert-file /tls/1.example.com.crt
      --tls-key-file /tls/1.example.com.key --tls-ca-cert-dir /etc/ssl/cert.pem
      --cluster-enabled yes --cluster-config-file /data/nodes.conf --cluster-node-timeout
      5000"
    volumes:
    - "/root/caddy/caddy_data/caddy/certificates/acme-v02.api.letsencrypt.org-directory/1.example.com/:/tls/"
    - "/root/data/redis/:/data/"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    logging:
      driver: json-file
      options:
        max-file: 1
        max-size: 50m
  reloader:
    container_name: reloader
    image: redis:8-alpine
    depends_on:
    - redis
    restart: always
    command:
    - "/bin/sh"
    - "-c"
    - while :; do sleep 10; redis-cli --no-auth-warning -u rediss://password@redis:6379
      CONFIG SET tls-cert-file /tls/1.example.com.crt > /dev/null; sleep 86400;
      done
    logging:
      driver: json-file
      options:
        max-file: 1
        max-size: 50m
```
